//go:build amd64 || arm64 || 386 || arm || wasm || mips64le || ppc64le || riscv64

// Code generated by litz-gen. DO NOT EDIT.
package litz_test

import (
	"strings"
	"unsafe"

	"github.com/cuprite-io/litz"
)

// singleKeyLitzMirror is the GC-safe layout mirror for SingleKey
type singleKeyLitzMirror struct {
	ID uint64
}

// Compile-time size assertions to guarantee layout identity
var _ [int(unsafe.Sizeof(SingleKey{})) - int(unsafe.Sizeof(singleKeyLitzMirror{}))]byte
var _ [int(unsafe.Sizeof(singleKeyLitzMirror{})) - int(unsafe.Sizeof(SingleKey{}))]byte
var _ [int(unsafe.Offsetof(SingleKey{}.ID)) - int(unsafe.Offsetof(singleKeyLitzMirror{}.ID))]byte
var _ [int(unsafe.Offsetof(singleKeyLitzMirror{}.ID)) - int(unsafe.Offsetof(SingleKey{}.ID))]byte

func MarshalSingleKey(u *SingleKey, buf []byte) ([]byte, error) {
	fixedSize := int(unsafe.Sizeof(singleKeyLitzMirror{}))
	totalSize := 8 + fixedSize

	// Ensure output buffer is aligned and large enough
	if cap(buf) < totalSize || (cap(buf) > 0 && uintptr(unsafe.Pointer(&buf[0]))%8 != 0) {
		buf = litz.AlignedBuffer(totalSize)
	}
	buf = buf[:totalSize]

	// Write 8-byte format signature: 'LTZ0' + Version 1
	*(*[4]byte)(unsafe.Pointer(&buf[0])) = [4]byte{'L', 'T', 'Z', '0'}
	buf[4] = 1
	buf[5] = 0
	buf[6] = 0
	buf[7] = 0

	// Write directly to the buffer's mirror pointer (O1 Optimization: No stack allocation/double-copy!)
	// Zero the fixed size header to prevent padding data leaks
	*(*singleKeyLitzMirror)(unsafe.Pointer(&buf[8])) = singleKeyLitzMirror{}
	mirror := (*singleKeyLitzMirror)(unsafe.Pointer(&buf[8]))

	mirror.ID = u.ID
	return buf, nil
}

// UnmarshalSingleKey deserializes the buffer using SBC-IPR.
// WARNING: Unmarshaled strings and slices point directly into buf.
// The input buf MUST outlive the returned structure u to prevent use-after-free corruption.
func UnmarshalSingleKey(buf []byte, u *SingleKey) error {
	if len(buf) < 8 {
		return litz.ErrBufferTooShort
	}
	if *(*[4]byte)(unsafe.Pointer(&buf[0])) != [4]byte{'L', 'T', 'Z', '0'} || buf[4] != 1 {
		return litz.ErrInvalidHeader
	}
	mirror := (*singleKeyLitzMirror)(unsafe.Pointer(&buf[8]))

	if 8+unsafe.Offsetof(mirror.ID)+unsafe.Sizeof(mirror.ID) <= uintptr(len(buf)) {
	}

	if 8+unsafe.Offsetof(mirror.ID)+unsafe.Sizeof(mirror.ID) <= uintptr(len(buf)) {
		u.ID = mirror.ID
	}

	return nil
}

// Clone creates a deep-copy of SingleKey, allocating fresh memory for all string and slice fields.
func (u *SingleKey) Clone() *SingleKey {
	res := new(SingleKey)
	res.ID = u.ID
	return res
}

// userProfileLitzMirror is the GC-safe layout mirror for UserProfile
type userProfileLitzMirror struct {
	Age   uint32
	Score float64
	Name  struct {
		offset uintptr
		length int
	}
	Active bool
}

// Compile-time size assertions to guarantee layout identity
var _ [int(unsafe.Sizeof(UserProfile{})) - int(unsafe.Sizeof(userProfileLitzMirror{}))]byte
var _ [int(unsafe.Sizeof(userProfileLitzMirror{})) - int(unsafe.Sizeof(UserProfile{}))]byte
var _ [int(unsafe.Offsetof(UserProfile{}.Age)) - int(unsafe.Offsetof(userProfileLitzMirror{}.Age))]byte
var _ [int(unsafe.Offsetof(userProfileLitzMirror{}.Age)) - int(unsafe.Offsetof(UserProfile{}.Age))]byte
var _ [int(unsafe.Offsetof(UserProfile{}.Score)) - int(unsafe.Offsetof(userProfileLitzMirror{}.Score))]byte
var _ [int(unsafe.Offsetof(userProfileLitzMirror{}.Score)) - int(unsafe.Offsetof(UserProfile{}.Score))]byte
var _ [int(unsafe.Offsetof(UserProfile{}.Name)) - int(unsafe.Offsetof(userProfileLitzMirror{}.Name))]byte
var _ [int(unsafe.Offsetof(userProfileLitzMirror{}.Name)) - int(unsafe.Offsetof(UserProfile{}.Name))]byte
var _ [int(unsafe.Offsetof(UserProfile{}.Active)) - int(unsafe.Offsetof(userProfileLitzMirror{}.Active))]byte
var _ [int(unsafe.Offsetof(userProfileLitzMirror{}.Active)) - int(unsafe.Offsetof(UserProfile{}.Active))]byte

func MarshalUserProfile(u *UserProfile, buf []byte) ([]byte, error) {
	fixedSize := int(unsafe.Sizeof(userProfileLitzMirror{}))
	totalSize := 8 + fixedSize

	NameLen := len(u.Name)
	if totalSize+NameLen < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += NameLen

	// Ensure output buffer is aligned and large enough
	if cap(buf) < totalSize || (cap(buf) > 0 && uintptr(unsafe.Pointer(&buf[0]))%8 != 0) {
		buf = litz.AlignedBuffer(totalSize)
	}
	buf = buf[:totalSize]

	// Write 8-byte format signature: 'LTZ0' + Version 1
	*(*[4]byte)(unsafe.Pointer(&buf[0])) = [4]byte{'L', 'T', 'Z', '0'}
	buf[4] = 1
	buf[5] = 0
	buf[6] = 0
	buf[7] = 0

	// Write directly to the buffer's mirror pointer (O1 Optimization: No stack allocation/double-copy!)
	// Zero the fixed size header to prevent padding data leaks
	*(*userProfileLitzMirror)(unsafe.Pointer(&buf[8])) = userProfileLitzMirror{}
	mirror := (*userProfileLitzMirror)(unsafe.Pointer(&buf[8]))

	mirror.Age = u.Age
	mirror.Score = u.Score
	mirror.Active = u.Active
	currentOffset := uintptr(8 + fixedSize)

	mirror.Name.offset = currentOffset
	mirror.Name.length = NameLen
	copy(buf[currentOffset:], u.Name)
	currentOffset += uintptr(NameLen)

	return buf, nil
}

// UnmarshalUserProfile deserializes the buffer using SBC-IPR.
// WARNING: Unmarshaled strings and slices point directly into buf.
// The input buf MUST outlive the returned structure u to prevent use-after-free corruption.
func UnmarshalUserProfile(buf []byte, u *UserProfile) error {
	if len(buf) < 8 {
		return litz.ErrBufferTooShort
	}
	if *(*[4]byte)(unsafe.Pointer(&buf[0])) != [4]byte{'L', 'T', 'Z', '0'} || buf[4] != 1 {
		return litz.ErrInvalidHeader
	}
	mirror := (*userProfileLitzMirror)(unsafe.Pointer(&buf[8]))

	if 8+unsafe.Offsetof(mirror.Age)+unsafe.Sizeof(mirror.Age) <= uintptr(len(buf)) {
	}
	if 8+unsafe.Offsetof(mirror.Score)+unsafe.Sizeof(mirror.Score) <= uintptr(len(buf)) {
	}
	if 8+unsafe.Offsetof(mirror.Name)+unsafe.Sizeof(mirror.Name) <= uintptr(len(buf)) {
		if mirror.Name.offset > uintptr(len(buf)) || mirror.Name.length < 0 || mirror.Name.length > len(buf)-int(mirror.Name.offset) {
			return litz.ErrStringOutOfBounds
		}
	}
	if 8+unsafe.Offsetof(mirror.Active)+unsafe.Sizeof(mirror.Active) <= uintptr(len(buf)) {
	}

	if 8+unsafe.Offsetof(mirror.Age)+unsafe.Sizeof(mirror.Age) <= uintptr(len(buf)) {
		u.Age = mirror.Age
	}
	if 8+unsafe.Offsetof(mirror.Score)+unsafe.Sizeof(mirror.Score) <= uintptr(len(buf)) {
		u.Score = mirror.Score
	}
	if 8+unsafe.Offsetof(mirror.Active)+unsafe.Sizeof(mirror.Active) <= uintptr(len(buf)) {
		u.Active = mirror.Active
	}
	if 8+unsafe.Offsetof(mirror.Name)+unsafe.Sizeof(mirror.Name) <= uintptr(len(buf)) {
		if mirror.Name.length > 0 {
			u.Name = unsafe.String((*byte)(unsafe.Add(unsafe.Pointer(&buf[0]), mirror.Name.offset)), mirror.Name.length)
		} else {
			u.Name = ""
		}
	}

	return nil
}

// Clone creates a deep-copy of UserProfile, allocating fresh memory for all string and slice fields.
func (u *UserProfile) Clone() *UserProfile {
	res := new(UserProfile)
	res.Age = u.Age
	res.Score = u.Score
	res.Name = strings.Clone(u.Name)
	res.Active = u.Active
	return res
}

// nestedPayloadLitzMirror is the GC-safe layout mirror for NestedPayload
type nestedPayloadLitzMirror struct {
	Profile  uintptr
	Metadata struct {
		offset  uintptr
		length  uint32
		valType uint32
	}
	Tags struct {
		offset   uintptr
		length   int
		capacity int
	}
	Numbers struct {
		offset   uintptr
		length   int
		capacity int
	}
	Signature struct {
		offset   uintptr
		length   int
		capacity int
	}
}

// Compile-time size assertions to guarantee layout identity
var _ [int(unsafe.Sizeof(NestedPayload{})) - int(unsafe.Sizeof(nestedPayloadLitzMirror{}))]byte
var _ [int(unsafe.Sizeof(nestedPayloadLitzMirror{})) - int(unsafe.Sizeof(NestedPayload{}))]byte
var _ [int(unsafe.Offsetof(NestedPayload{}.Profile)) - int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Profile))]byte
var _ [int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Profile)) - int(unsafe.Offsetof(NestedPayload{}.Profile))]byte
var _ [int(unsafe.Offsetof(NestedPayload{}.Metadata)) - int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Metadata))]byte
var _ [int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Metadata)) - int(unsafe.Offsetof(NestedPayload{}.Metadata))]byte
var _ [int(unsafe.Offsetof(NestedPayload{}.Tags)) - int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Tags))]byte
var _ [int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Tags)) - int(unsafe.Offsetof(NestedPayload{}.Tags))]byte
var _ [int(unsafe.Offsetof(NestedPayload{}.Numbers)) - int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Numbers))]byte
var _ [int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Numbers)) - int(unsafe.Offsetof(NestedPayload{}.Numbers))]byte
var _ [int(unsafe.Offsetof(NestedPayload{}.Signature)) - int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Signature))]byte
var _ [int(unsafe.Offsetof(nestedPayloadLitzMirror{}.Signature)) - int(unsafe.Offsetof(NestedPayload{}.Signature))]byte

func MarshalNestedPayload(u *NestedPayload, buf []byte) ([]byte, error) {
	fixedSize := int(unsafe.Sizeof(nestedPayloadLitzMirror{}))
	totalSize := 8 + fixedSize

	var ProfileBytes []byte
	if u.Profile != nil {
		var err error
		ProfileBytes, err = MarshalUserProfile(u.Profile, nil)
		if err != nil {
			return nil, err
		}
	}
	ProfileLen := len(ProfileBytes)
	if totalSize+ProfileLen < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += ProfileLen
	MetadataBytes, MetadataType, err := litz.MarshalAny(u.Metadata)
	if err != nil {
		return nil, err
	}
	MetadataLen := len(MetadataBytes)
	if totalSize+MetadataLen < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += MetadataLen
	TagsLen := len(u.Tags)
	// Slice array of string headers (size of Go string header)
	TagsHeaderSize := TagsLen * int(unsafe.Sizeof(""))
	if TagsLen > 0 && TagsHeaderSize/TagsLen != int(unsafe.Sizeof("")) {
		return nil, litz.ErrSizeOverflow
	}
	if totalSize+TagsHeaderSize < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += TagsHeaderSize
	// Add string backing bytes
	for i := 0; i < TagsLen; i++ {
		strLen := len(u.Tags[i])
		if totalSize+strLen < totalSize {
			return nil, litz.ErrSizeOverflow
		}
		totalSize += strLen
	}
	NumbersLen := len(u.Numbers)
	var NumbersDummy int
	NumbersSize := NumbersLen * int(unsafe.Sizeof(NumbersDummy))
	if NumbersLen > 0 && NumbersSize/NumbersLen != int(unsafe.Sizeof(NumbersDummy)) {
		return nil, litz.ErrSizeOverflow
	}
	if totalSize+NumbersSize < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += NumbersSize
	SignatureLen := len(u.Signature)
	if totalSize+SignatureLen < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += SignatureLen

	// Ensure output buffer is aligned and large enough
	if cap(buf) < totalSize || (cap(buf) > 0 && uintptr(unsafe.Pointer(&buf[0]))%8 != 0) {
		buf = litz.AlignedBuffer(totalSize)
	}
	buf = buf[:totalSize]

	// Write 8-byte format signature: 'LTZ0' + Version 1
	*(*[4]byte)(unsafe.Pointer(&buf[0])) = [4]byte{'L', 'T', 'Z', '0'}
	buf[4] = 1
	buf[5] = 0
	buf[6] = 0
	buf[7] = 0

	// Write directly to the buffer's mirror pointer (O1 Optimization: No stack allocation/double-copy!)
	// Zero the fixed size header to prevent padding data leaks
	*(*nestedPayloadLitzMirror)(unsafe.Pointer(&buf[8])) = nestedPayloadLitzMirror{}
	mirror := (*nestedPayloadLitzMirror)(unsafe.Pointer(&buf[8]))

	currentOffset := uintptr(8 + fixedSize)

	if ProfileLen > 0 {
		mirror.Profile = currentOffset
		copy(buf[currentOffset:], ProfileBytes)
		currentOffset += uintptr(ProfileLen)
	} else {
		mirror.Profile = 0
	}

	mirror.Metadata.offset = currentOffset
	mirror.Metadata.length = uint32(MetadataLen)
	mirror.Metadata.valType = uint32(MetadataType)
	copy(buf[currentOffset:], MetadataBytes)
	currentOffset += uintptr(MetadataLen)

	mirror.Tags.offset = currentOffset
	mirror.Tags.length = TagsLen
	mirror.Tags.capacity = TagsLen
	if TagsLen > 0 {
		// First reserve space for slice of string headers (16B each)
		strArrayOffset := currentOffset
		currentOffset += uintptr(TagsLen * 16)
		// Write string bytes and fill array headers
		for i := 0; i < TagsLen; i++ {
			strLen := len(u.Tags[i])
			copy(buf[currentOffset:], u.Tags[i])
			// Fill header in slice array
			entryPtr := strArrayOffset + uintptr(i*16)
			*(*uintptr)(unsafe.Pointer(&buf[entryPtr])) = currentOffset
			*(*int)(unsafe.Pointer(&buf[entryPtr+8])) = strLen
			currentOffset += uintptr(strLen)
		}
	}

	mirror.Numbers.offset = currentOffset
	mirror.Numbers.length = NumbersLen
	mirror.Numbers.capacity = cap(u.Numbers)
	if NumbersLen > 0 {
		varSize := NumbersLen * int(unsafe.Sizeof(NumbersDummy))
		sliceBytes := unsafe.Slice((*byte)(unsafe.Pointer(&u.Numbers[0])), varSize)
		copy(buf[currentOffset:], sliceBytes)
		currentOffset += uintptr(varSize)
	}

	mirror.Signature.offset = currentOffset
	mirror.Signature.length = SignatureLen
	mirror.Signature.capacity = cap(u.Signature)
	copy(buf[currentOffset:], u.Signature)
	currentOffset += uintptr(SignatureLen)

	return buf, nil
}

// UnmarshalNestedPayload deserializes the buffer using SBC-IPR.
// WARNING: Unmarshaled strings and slices point directly into buf.
// The input buf MUST outlive the returned structure u to prevent use-after-free corruption.
func UnmarshalNestedPayload(buf []byte, u *NestedPayload) error {
	if len(buf) < 8 {
		return litz.ErrBufferTooShort
	}
	if *(*[4]byte)(unsafe.Pointer(&buf[0])) != [4]byte{'L', 'T', 'Z', '0'} || buf[4] != 1 {
		return litz.ErrInvalidHeader
	}
	mirror := (*nestedPayloadLitzMirror)(unsafe.Pointer(&buf[8]))

	if 8+unsafe.Offsetof(mirror.Profile)+unsafe.Sizeof(mirror.Profile) <= uintptr(len(buf)) {
		if mirror.Profile > uintptr(len(buf)) || (mirror.Profile > 0 && uintptr(len(buf))-mirror.Profile < unsafe.Sizeof(userProfileLitzMirror{})) {
			return litz.ErrPointerOutOfBounds
		}
	}
	if 8+unsafe.Offsetof(mirror.Metadata)+unsafe.Sizeof(mirror.Metadata) <= uintptr(len(buf)) {
		if mirror.Metadata.offset > uintptr(len(buf)) || mirror.Metadata.length < 0 || int(mirror.Metadata.length) > len(buf)-int(mirror.Metadata.offset) {
			return litz.ErrStringOutOfBounds
		}
	}
	if 8+unsafe.Offsetof(mirror.Tags)+unsafe.Sizeof(mirror.Tags) <= uintptr(len(buf)) {
		if mirror.Tags.offset > uintptr(len(buf)) || mirror.Tags.length < 0 || mirror.Tags.length > (len(buf)-int(mirror.Tags.offset))/int(unsafe.Sizeof("")) {
			return litz.ErrSliceOutOfBounds
		}
	}
	if 8+unsafe.Offsetof(mirror.Numbers)+unsafe.Sizeof(mirror.Numbers) <= uintptr(len(buf)) {
		var NumbersDummy int
		if mirror.Numbers.offset > uintptr(len(buf)) || mirror.Numbers.length < 0 || mirror.Numbers.length > (len(buf)-int(mirror.Numbers.offset))/int(unsafe.Sizeof(NumbersDummy)) {
			return litz.ErrSliceOutOfBounds
		}
	}
	if 8+unsafe.Offsetof(mirror.Signature)+unsafe.Sizeof(mirror.Signature) <= uintptr(len(buf)) {
		if mirror.Signature.offset > uintptr(len(buf)) || mirror.Signature.length < 0 || mirror.Signature.length > len(buf)-int(mirror.Signature.offset) {
			return litz.ErrSliceOutOfBounds
		}
	}

	if 8+unsafe.Offsetof(mirror.Profile)+unsafe.Sizeof(mirror.Profile) <= uintptr(len(buf)) {
		if mirror.Profile > 0 {
			if u.Profile == nil {
				u.Profile = new(UserProfile)
			}
			err := UnmarshalUserProfile(buf[mirror.Profile:], u.Profile)
			if err != nil {
				return err
			}
		} else {
			u.Profile = nil
		}
	}
	if 8+unsafe.Offsetof(mirror.Metadata)+unsafe.Sizeof(mirror.Metadata) <= uintptr(len(buf)) {
		if mirror.Metadata.length > 0 {
			u.Metadata = litz.NewDynamic(buf[mirror.Metadata.offset:mirror.Metadata.offset+uintptr(mirror.Metadata.length)], uint8(mirror.Metadata.valType))
		} else {
			u.Metadata = nil
		}
	}
	if 8+unsafe.Offsetof(mirror.Tags)+unsafe.Sizeof(mirror.Tags) <= uintptr(len(buf)) {
		if mirror.Tags.length > 0 {
			strHeaders := unsafe.Slice((*struct {
				offset uintptr
				length int
			})(unsafe.Add(unsafe.Pointer(&buf[0]), mirror.Tags.offset)), mirror.Tags.length)
			maxExtent := 0
			for i := 0; i < len(strHeaders); i++ {
				endOffset := int(strHeaders[i].offset) + strHeaders[i].length
				if endOffset > maxExtent {
					maxExtent = endOffset
				}
			}
			if maxExtent > len(buf) {
				return litz.ErrStringOutOfBounds
			}
			slice := make([]string, len(strHeaders))
			for i := 0; i < len(strHeaders); i++ {
				if strHeaders[i].length > 0 {
					slice[i] = unsafe.String((*byte)(unsafe.Add(unsafe.Pointer(&buf[0]), strHeaders[i].offset)), strHeaders[i].length)
				}
			}
			u.Tags = slice
		} else {
			u.Tags = nil
		}
	}
	if 8+unsafe.Offsetof(mirror.Numbers)+unsafe.Sizeof(mirror.Numbers) <= uintptr(len(buf)) {
		if mirror.Numbers.length > 0 {
			u.Numbers = unsafe.Slice((*int)(unsafe.Add(unsafe.Pointer(&buf[0]), mirror.Numbers.offset)), mirror.Numbers.length)
		} else {
			u.Numbers = nil
		}
	}
	if 8+unsafe.Offsetof(mirror.Signature)+unsafe.Sizeof(mirror.Signature) <= uintptr(len(buf)) {
		if mirror.Signature.length > 0 {
			u.Signature = unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(&buf[0]), mirror.Signature.offset)), mirror.Signature.length)
		} else {
			u.Signature = nil
		}
	}

	return nil
}

// Clone creates a deep-copy of NestedPayload, allocating fresh memory for all string and slice fields.
func (u *NestedPayload) Clone() *NestedPayload {
	res := new(NestedPayload)
	if u.Profile != nil {
		res.Profile = u.Profile.Clone()
	}
	res.Metadata = litz.CloneAny(u.Metadata)
	if u.Tags != nil {
		res.Tags = make([]string, len(u.Tags))
		for i := 0; i < len(u.Tags); i++ {
			res.Tags[i] = strings.Clone(u.Tags[i])
		}
	}
	if u.Numbers != nil {
		res.Numbers = make([]int, len(u.Numbers))
		copy(res.Numbers, u.Numbers)
	}
	if u.Signature != nil {
		res.Signature = make([]byte, len(u.Signature))
		copy(res.Signature, u.Signature)
	}
	return res
}

// outerMessageLitzMirror is the GC-safe layout mirror for OuterMessage
type outerMessageLitzMirror struct {
	SeqNum uint64
	Body   uintptr
}

// Compile-time size assertions to guarantee layout identity
var _ [int(unsafe.Sizeof(OuterMessage{})) - int(unsafe.Sizeof(outerMessageLitzMirror{}))]byte
var _ [int(unsafe.Sizeof(outerMessageLitzMirror{})) - int(unsafe.Sizeof(OuterMessage{}))]byte
var _ [int(unsafe.Offsetof(OuterMessage{}.SeqNum)) - int(unsafe.Offsetof(outerMessageLitzMirror{}.SeqNum))]byte
var _ [int(unsafe.Offsetof(outerMessageLitzMirror{}.SeqNum)) - int(unsafe.Offsetof(OuterMessage{}.SeqNum))]byte
var _ [int(unsafe.Offsetof(OuterMessage{}.Body)) - int(unsafe.Offsetof(outerMessageLitzMirror{}.Body))]byte
var _ [int(unsafe.Offsetof(outerMessageLitzMirror{}.Body)) - int(unsafe.Offsetof(OuterMessage{}.Body))]byte

func MarshalOuterMessage(u *OuterMessage, buf []byte) ([]byte, error) {
	fixedSize := int(unsafe.Sizeof(outerMessageLitzMirror{}))
	totalSize := 8 + fixedSize

	var BodyBytes []byte
	if u.Body != nil {
		var err error
		BodyBytes, err = MarshalNestedPayload(u.Body, nil)
		if err != nil {
			return nil, err
		}
	}
	BodyLen := len(BodyBytes)
	if totalSize+BodyLen < totalSize {
		return nil, litz.ErrSizeOverflow
	}
	totalSize += BodyLen

	// Ensure output buffer is aligned and large enough
	if cap(buf) < totalSize || (cap(buf) > 0 && uintptr(unsafe.Pointer(&buf[0]))%8 != 0) {
		buf = litz.AlignedBuffer(totalSize)
	}
	buf = buf[:totalSize]

	// Write 8-byte format signature: 'LTZ0' + Version 1
	*(*[4]byte)(unsafe.Pointer(&buf[0])) = [4]byte{'L', 'T', 'Z', '0'}
	buf[4] = 1
	buf[5] = 0
	buf[6] = 0
	buf[7] = 0

	// Write directly to the buffer's mirror pointer (O1 Optimization: No stack allocation/double-copy!)
	// Zero the fixed size header to prevent padding data leaks
	*(*outerMessageLitzMirror)(unsafe.Pointer(&buf[8])) = outerMessageLitzMirror{}
	mirror := (*outerMessageLitzMirror)(unsafe.Pointer(&buf[8]))

	mirror.SeqNum = u.SeqNum
	currentOffset := uintptr(8 + fixedSize)

	if BodyLen > 0 {
		mirror.Body = currentOffset
		copy(buf[currentOffset:], BodyBytes)
		currentOffset += uintptr(BodyLen)
	} else {
		mirror.Body = 0
	}

	return buf, nil
}

// UnmarshalOuterMessage deserializes the buffer using SBC-IPR.
// WARNING: Unmarshaled strings and slices point directly into buf.
// The input buf MUST outlive the returned structure u to prevent use-after-free corruption.
func UnmarshalOuterMessage(buf []byte, u *OuterMessage) error {
	if len(buf) < 8 {
		return litz.ErrBufferTooShort
	}
	if *(*[4]byte)(unsafe.Pointer(&buf[0])) != [4]byte{'L', 'T', 'Z', '0'} || buf[4] != 1 {
		return litz.ErrInvalidHeader
	}
	mirror := (*outerMessageLitzMirror)(unsafe.Pointer(&buf[8]))

	if 8+unsafe.Offsetof(mirror.SeqNum)+unsafe.Sizeof(mirror.SeqNum) <= uintptr(len(buf)) {
	}
	if 8+unsafe.Offsetof(mirror.Body)+unsafe.Sizeof(mirror.Body) <= uintptr(len(buf)) {
		if mirror.Body > uintptr(len(buf)) || (mirror.Body > 0 && uintptr(len(buf))-mirror.Body < unsafe.Sizeof(nestedPayloadLitzMirror{})) {
			return litz.ErrPointerOutOfBounds
		}
	}

	if 8+unsafe.Offsetof(mirror.SeqNum)+unsafe.Sizeof(mirror.SeqNum) <= uintptr(len(buf)) {
		u.SeqNum = mirror.SeqNum
	}
	if 8+unsafe.Offsetof(mirror.Body)+unsafe.Sizeof(mirror.Body) <= uintptr(len(buf)) {
		if mirror.Body > 0 {
			if u.Body == nil {
				u.Body = new(NestedPayload)
			}
			err := UnmarshalNestedPayload(buf[mirror.Body:], u.Body)
			if err != nil {
				return err
			}
		} else {
			u.Body = nil
		}
	}

	return nil
}

// Clone creates a deep-copy of OuterMessage, allocating fresh memory for all string and slice fields.
func (u *OuterMessage) Clone() *OuterMessage {
	res := new(OuterMessage)
	res.SeqNum = u.SeqNum
	if u.Body != nil {
		res.Body = u.Body.Clone()
	}
	return res
}
